### PR TITLE
Update project & add restrictions for branch protection

### LINKED ISSUE #17: why can't I set restrictions for users and/or teams

### PR DESCRIPTION
**Pull request by pavlospt**
Resolves #17

### CODE REVIEW

**Review by charbgr — APPROVED** [review]

**Comment by aberenshtein** [comment]
Very nice!
But why is the github action hardcoded?

I want to set up branch protection when adding a label on a PR  @pavlospt

**Comment by pavlospt** [comment]
What do you mean hardcoded?

**Comment by aberenshtein** [comment]
The GitHub action is only triggered on create and delete
https://github.com/infamous-riddles/branch-guardian/blob/master/src/action_processor.ts#L45

**Comment by aberenshtein** [comment]
Can it be an ENV var?
ACTION: create/delete

**Comment by pavlospt** [comment]
This is what it was designed for. If you need another feature, feel free to submit a PR 😄

**Pull request merged**
